#!/usr/bin/env bash
# install and setup HAProxy on brand new server

function install_haproxy {
	sudo apt-get install -y --no-install-recommends software-properties-common
	sudo add-apt-repository -y ppa:vbernat/haproxy-2.2
	sudo apt update -y
	sudo apt-get install -y haproxy=2.2.\*
}

if [ "$(dpkg -l haproxy | grep -c "load balancing")" -ne 0 ]; then
	if [ "$(dpkg -l haproxy | grep -c "2.2")" -eq 0 ]; then
		install_haproxy
	fi
else
	install_haproxy
fi


INIT_FILE="/etc/default/haproxy"
CONFIG_FILE="/etc/haproxy/haproxy.cfg"
DOMAIN="isaacsweb.tech"
cfg_start="#----$DOMAIN-config-begin----"
cfg_end="#----$DOMAIN-config-end----"


[ -f "INIT_FILE" ] || sudo touch "$INIT_FILE"
[ -f "CONFIG_FILE" ] || sudo touch "$CONFIG_FILE"

# servers
WEB01="54.90.2.85"
WEB02="3.84.222.8"

# haproxy config
CONFIG=\
"
$cfg_start
frontend http
	bind *:80
	option forwardfor
	default_backend web_backend

backend web_backend
	balance roundrobin
	server web01 $WEB01:80 check
	server web02 $WEB02:80 check
$cfg_end
"

if [ $(sudo grep -co "$cfg_start" $CONFIG_FILE) -ge 1 ]; then
	a="$(sudo grep -no "$cfg_start" $CONFIG_FILE | cut -d : -f1 )"
	b="$(sudo grep -no "$cfg_end" $CONFIG_FILE | cut -d : -f1)"
	ln1=$((a - 1))
	ln2=$((b + 1))
	sudo sed -i "$ln1,$ln2"d $CONFIG_FILE
	echo -en "$CONFIG" | sudo tee -a $CONFIG_FILE
else
	echo -en "$CONFIG" | sudo tee -a $CONFIG_FILE
fi

if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_FILE)" -gt 0 ]; then
        sudo sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
        echo 'ENABLED=1' | sudo -a tee $INIT_FILE
fi


if [ "$(pgrep -cf haproxy)" -eq 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
