#!/usr/bin/env bash
# install and setup HAProxy on brand new server
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.2
sudo apt update -y
sudo apt-get install -y haproxy=2.2.\*

INIT_FILE="/etc/default/haproxy"

# configure HAProxy
WEB01="52.205.39.23"
WEB02="54.208.125.127"
CONFIG=\
"
frontend http
	bind *:80
	option forwardfor
	default_backend web_backend

backend web_backend
	balance roundrobin
	server web01 $WEB01:80 check
	server web02 $WEB02:80 check
"

if [ "$(grep -c $WEB01 /etc/haproxy/haproxy.cfg)" -eq 0 ]; then
	echo -e "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg
fi

[ -f "INIT_FILE" ] || touch "$INIT_FILE"

if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_FILE)" -gt 0 ]; then
        sudo sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
        echo 'ENABLED=1' | sudo tee $INIT_FILE
fi


if [ "$(pgrep -cf haproxy)" -eq 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
