#!/usr/bin/env bash
wget https://dev.mysql.com/get/mysql-apt-config_0.8.12-1_all.deb
sudo dpkg -i mysql-apt-config_0.8.12-1_all.deb
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 467B942D3A79BD29
sudo apt update
sudo apt install -yf mysql-client=5.7* mysql-community-server=5.7* mysql-server=5.7*
sudo service mysql start
if [ "$(pgrep -cf ufw)" -eq 0 ]; then
	sudo ufw enable
	sudo ufw allow ssh
	sudo ufw allow mysql
	sudo ufw reload
else
	sudo ufw allow mysql
	sudo ufw reload
fi
